### ISSUE TITLE
jit-grunt: plugin for the wakeup task not found

### ISSUE THREAD

**Issue by oldlastman** [elegantthemes/divi-child-theme-init#1]
Hi,
i cloned this repo and made "npm install" , i could read some warning but nothing special important.
Them i start "grunt" and appeared this error
jit-grunt: Plugin for the "wakeup" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

so, i installed the plugin
npm install grunt-wakeup --save-dev

and again, launched grunt
this time all looks right.

in package.json i couldn't find grunt-wakeup, this is a little error or something in my config is wrong?
my config:
- ubuntu
- npm v 3.7.5
- node -v 5.4.1
- grunt-cli v 0.1.13
  ## thanks
  
  Make sure these boxes are checked before submitting your issue.
- [ x] You are using this for WordPress.
- [x] You have Divi installed.
- [ x] You have lint your code to ensure the problem isn't caused by your code.
- [ x] You have already searched the GitHub issues and it has not been reported before.
##

**Comment by andyhqtran** [comment]
@oldlastman Thanks for pointing this out. It looks like I forgot to save the wakeup package when I moved the settings over from my repo.
